name: Checkmarx SCA Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  checkmarx-sca:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Checkmarx SCA Resolver
        run: |
          Invoke-WebRequest -OutFile ScaResolver-win64.zip -URI https://sca-downloads.s3.amazonaws.com/cli/1.13.4/ScaResolver-win64.zip
          tar.exe -xf ScaResolver-win64.zip
          Remove-Item ScaResolver-win64.zip
        shell: pwsh

      - name: Install NuGet
        uses: NuGet/setup-nuget@v1

      - name: Run Checkmarx AST SCA Scan
        env:
          CHECKMARX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID }}
          CHECKMARX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
#          CHECKMARX_API_BASE_URL: ${{ secrets.CX_API_URL }}
          CHECKMARX_TENANT: ast_abdul_ansari
        run: |
          ./ScaResolver/sca-resolver.exe \
            --project-name "${{ github.event.repository.name }}" \
            --branch "${{ github.head_ref || github.ref_name }}" \
            --base-url "${{ env.CHECKMARX_API_BASE_URL }}" \
            --tenant "${{ env.CHECKMARX_TENANT }}" \
            --client-id "${{ env.CHECKMARX_CLIENT_ID }}" \
            --client-secret "${{ env.CHECKMARX_CLIENT_SECRET }}"
