name: Checkmarx SCA Scan
 
on:
  push:
    branches:
      [main]
  pull_request:
    branches:
      [main]
 
jobs:
  sca-scan:
    name: Download and Extract CxSCA Resolver
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
 
      - name: Download and extract CxSCA Resolver (Linux)
        run: |
          curl -L -o ScaResolver-linux64.tar.gz https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzf ScaResolver-linux64.tar.gz
          chmod 755 ./ScaResolver  # Ensure proper permissions
          ls -l ./ScaResolver  # Verify permissions
          ./ScaResolver --help  # Test executable
 
      - name: Upload CxSCA Resolver as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScaResolver
          path: ./ScaResolver
 
  ast-scan:
    name: Run Checkmarx AST Scan using CLI
    runs-on: ubuntu-latest
    needs: sca-scan
 
    steps:
 
      - name: Download CxSCA Resolver artifact
        uses: actions/download-artifact@v4
        with:
          name: ScaResolver
 
      - name: Verify artifact location and permissions
        run: |
          echo "Listing contents of the workspace directory to verify artifact download:"
          ls -l /home/runner/work/webgoathg/webgoathg  # Typical path for artifact downloads
          echo "Listing contents of ScaResolver location:"
          ls -l /home/runner/work/webgoathg/webgoathg/ScaResolver  # Verify artifact is here
          echo "Checking if ScaResolver is an executable:"
          file /home/runner/work/webgoathg/webgoathg/ScaResolver  # Verify it's a valid executable
 
      - name: Setting up permissions for resover
        run: |
          echo "Setting up proper permissions on ScaResolver:"
          sudo chmod 755 /home/runner/work/webgoathg/webgoathg/ScaResolver  # Ensure executable permissions inside Docker container
          ls -l /home/runner/work/webgoathg/webgoathg/ScaResolver  # Verify file is executable inside Docker
 
      - name: Install Homebrew and Checkmarx AST CLI
        run: |
          # Install Homebrew
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # Install Checkmarx AST CLI
          /home/linuxbrew/.linuxbrew/bin/brew install checkmarx/ast-cli/ast-cli
 
      - name: Run Checkmarx AST Scan
        run: |
          /home/linuxbrew/.linuxbrew/Cellar/ast-cli/*/bin/cx scan create \
            -s https://github.com/hdgokani/webgoathg \
            --agent GitHub \
            --project-name ${{ github.repository }} \
            --branch ${GITHUB_REF##*/} \
            --base-uri https://eu.ast.checkmarx.net/ \
            --tenant ast_abdul_ansari \
            --client-id HarshGJ1 \
            --client-secret dOhXWgcV6dy0jB3qVhqfmIn5n7pUnmrm \
            --scan-types sca \
            --sca-resolver /home/runner/work/webgoathg/webgoathg/ScaResolver \
            --report-sbom-format CycloneDxJson 
