name: Checkmarx SCA Scan (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sca-scan:
    name: Run CxSCA Scan using Windows Resolver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download and extract CxSCA Resolver (Windows)
        run: |
          curl -L -o ScaResolver-musl64.tar.gz https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-musl64.tar.gz
          tar -xzf ScaResolver-musl64.tar.gz

      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@749fec53e0db0f6404a97e2e0807c3e80e3583a7
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          # Provide the AST portal URL
          base_uri: https://eu.ast.checkmarx.net
          # Provide the Tenant for AST portal URL
          cx_tenant: ast_abdul_ansari
          # Client ID for AST portal authentication
          cx_client_id: HarshGJ1
          # Secret key for AST portal authentication
          cx_client_secret: dOhXWgcV6dy0jB3qVhqfmIn5n7pUnmrm
          # Additional parameters for AST scan
          additional_params: '--sca-resolver ./ScaResolver'
          # Repository name for PR decoration
         
